title: 박수진의 개발자 블로그
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# permalink: ':title/'
baseurl: "/gitblog" # the subpath of your site, e.g. /blog
url: "https://sujin-park0607.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sujin # add your name
author-img: sujinImg.jpg # add your photo
about-author: 적당히보다는 최선을 추구하는 개발자 박수진 입니다. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: sujin-park0607 # add your Github handle
social-linkedin: sujin # add your Linkedin handle
social-email: goweg0607@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: Sujin
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
